spring:
  project : InternSubject
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:tcp://localhost/~/intern-subject
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
